name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.4
        with:
          secrets: ${{ secrets.GCS_SERVICE_ACCOUNT }}
          bucket: 'hw6_q1'
          sync_dir_from: '/data'
          sync_dir_to: 'data'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
